robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - prism_joint
    - rot_1_joint
    - rot_2_joint
  gains:
    prism_joint:
      p: 10.0
      i: 0.01
      d: 0.0
    rot_1_joint:
      p: 10.0
      i: 0.01
      d: 0.0
    rot_2_joint:
      p: 10.0
      i: 0.01
      d: 0.0

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
